create table public.reviews (
  id bigint generated by default as identity not null,
  order_id text not null,
  name text null,
  stars integer not null,
  message text null,
  created_at timestamp with time zone null default now(),
  image_url text null,
  constraint reviews_pkey primary key (id),
  constraint reviews_stars_check check (
    (
      (stars >= 1)
      and (stars <= 5)
    )
  )
) TABLESPACE pg_default;